#!/usr/bin/env python
#
# Collects the recorded SRC_URI values from buildhistory and reports on them
#
# Copyright 2013 LG Electronics, Inc.
#
# Based on buildhistory-collect-srcrevs from branch=dylan,commit=e174486 of oe-core
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

import os, sys
import optparse
import logging

def logger_create():
    logger = logging.getLogger("buildhistory")
    loggerhandler = logging.StreamHandler()
    loggerhandler.setFormatter(logging.Formatter("%(levelname)s: %(message)s"))
    logger.addHandler(loggerhandler)
    logger.setLevel(logging.INFO)
    return logger

logger = logger_create()

def main():
    parser = optparse.OptionParser(
        usage = """
    %prog <buildhistory-dir>""")

    options, args = parser.parse_args(sys.argv)

    if len(args) != 2:
        parser.print_help()
        sys.exit(1)

    buildhistory_dir = args[1]
    if not os.path.exists(buildhistory_dir):
        logger.error('specified buildhistory path %s could not be found' % buildhistory_dir)
        sys.exit(1)

    for root, dirs, files in os.walk(buildhistory_dir):
        if '.git' in dirs:
            dirs.remove('.git')
        for fn in files:
            if fn == 'latest':
                fullpath = os.path.join(root, fn)
                pn = os.path.basename(root)
                src_uri = None
                with open(fullpath) as f:
                    for line in f:
                        if '=' in line:
                            splitval = line.split('=',1)
                            value = splitval[1].strip('" \t\n\r')
                        if line.startswith('SRC_URI = '):
                            src_uri = value
                if src_uri:
                    print('SRC_URI_pn-%s = %s' % (pn, src_uri))


if __name__ == "__main__":
    main()
